stages:
  download:
    cmd: python3 src/download.py data localhost 27017 artie_u ArtieU123 artie
    deps:
    - src/download.py
    outs:
    - data/pedagogicalinterventions.json
    frozen: true
  transformation:
    cmd: python3 src/formatcsv.py data/pedagogicalinterventions.json 
      data/pedagogicalinterventions.csv
    deps:
    - data/pedagogicalinterventions.json
    - src/formatcsv.py
    outs:
    - data/pedagogicalinterventions.csv
  transformationdr:
    cmd: python3 src/formatcsv_datarobot.py data/pedagogicalinterventions.json 
      data/pedagogicalinterventions_datarobot.csv
    deps:
    - data/pedagogicalinterventions.json
    - src/formatcsv.py
    outs:
    - data/pedagogicalinterventions_datarobot.csv
    frozen: true
  dataanalysis:
    cmd: python3 src/data_analysis.py params.yaml data/pedagogicalinterventions.csv
      dvc_plots/class_distribution.png data/class_distribution_summary.csv
    deps:
      - data/pedagogicalinterventions.csv
      - src/data_analysis.py
    outs:
      - dvc_plots/shap_feature_importance_bar.png
      - dvc_plots/shap_feature_importance_beeswarm.png
      - dvc_plots/shap_feature_importance_waterfall.png
      - data/shap_feature_importance.csv
  featureselection:
    cmd: python3 src/featureselection.py params.yaml 
      data/pedagogicalinterventions.csv data/featureselection.csv 
      data/selectedfeatures.csv
    deps:
    - data/pedagogicalinterventions.csv
    - src/featureselection.py
    params:
    - selection.drop_columns
    - selection.high_correlation
    - selection.method
    - selection.number_of_features
    - selection.target
    outs:
    - data/featureselection.csv
    - data/selectedfeatures.csv
    - dvc_plots/heatmap_correlation_after.png
    - dvc_plots/heatmap_correlation_before.png
  train:
    cmd: python3 src/train.py params.yaml data/featureselection.csv 
      model/help_model.keras metrics/plots.csv metrics/scores.json true
    deps:
    - data/featureselection.csv
    - src/train.py
    params:
    - model.dropout_value
    - model.lstm_units
    - model.mask_value
    - model.percentage_train_size
    - model.return_sequences
    - model.second_lstm_layer
    - model.training_batch_size
    - model.training_epochs
    - model.use_dropouts
    - model.use_bidirectional
    - model.initial_learning_rate
    - model.training_class_weights
    - model.training_early_stopping_patience
    - model.training_reduce_lr_patience
    - model.training_reduce_lr_factor
    - model.show_summary
    outs:
    - model/help_model.keras
    - images/model.png
    metrics:
    - metrics/scores.json:
        cache: false
    plots:
    - metrics/plots.csv
