stages:
  download:
    cmd: python src/download.py data prod.artie.rocks 27017 artie_u ArtieU123! artie
    deps:
    - src/download.py
    outs:
    - data/pedagogicalinterventions.json
  transformation:
    cmd: python3 src/formatcsv.py data/pedagogicalinterventions.json data/pedagogicalinterventions.csv
    deps:
    - data/pedagogicalinterventions.json
    - src/formatcsv.py
    outs:
    - data/pedagogicalinterventions.csv
  featureselection:
    cmd: python3 src/featureselection.py params.yaml data/pedagogicalinterventions.csv
      data/featureselection.csv
    deps:
    - data/pedagogicalinterventions.csv
    - src/featureselection.py
    params:
    - selection.drop_columns
    - selection.high_correlation
    - selection.method
    - selection.number_of_features
    - selection.target
    outs:
    - data/featureselection.csv
