stages:
  download:
    cmd: python src/download.py data prod.artie.rocks 27017 artie_u ArtieU123! artie
    deps:
    - src/download.py
    outs:
    - data/pedagogicalinterventions.json
  transformation:
    cmd: python3 src/formatcsv.py data/pedagogicalinterventions.json data/pedagogicalinterventions.csv
    deps:
    - data/pedagogicalinterventions.json
    - src/formatcsv.py
    outs:
    - data/pedagogicalinterventions.csv
  featureselection:
    cmd: python3 src/featureselection.py params.yaml data/pedagogicalinterventions.csv
      data/featureselection.csv data/selectedfeatures.csv
    deps:
    - data/pedagogicalinterventions.csv
    - src/featureselection.py
    params:
    - selection.drop_columns
    - selection.high_correlation
    - selection.method
    - selection.number_of_features
    - selection.target
    outs:
    - data/featureselection.csv
    - data/selectedfeatures.csv
  train:
    cmd: python3 src/train.py params.yaml data/featureselection.csv model/help_model.h5
      metrics/plots.csv metrics/scores.json
    deps:
    - data/featureselection.csv
    - src/train.py
    params:
    - model.dropout_value
    - model.lstm_units
    - model.mask_value
    - model.percentage_train_size
    - model.return_sequences
    - model.second_lstm_layer
    - model.training_batch_size
    - model.training_epochs
    - model.use_dropouts
    outs:
    - model/help_model.h5
    metrics:
    - metrics/scores.json:
        cache: false
    plots:
    - metrics/plots.csv
