stages:
  download:
    cmd: python src/download.py data pre-prod.artie.rocks 27017 artie_u ArtieU123
      artie
    deps:
    - src/download.py
    outs:
    - data/pedagogicalinterventions.json
  transformation:
    cmd: python3 src/formatcsv.py data/pedagogicalinterventions.json data/pedagogicalinterventions.csv
    deps:
    - data/pedagogicalinterventions.json
    - src/formatcsv.py
    outs:
    - data/pedagogicalinterventions.csv
