selection:
  method: filter
  target: request_help
  number_of_features: 50
  high_correlation: 0.90
  drop_columns: [exercise_is_evaluation, valid_solution, finished_exercise, exercise_skill_paralellism,
    exercise_valid_solution, student_motivation]

model:
  mask_value: -1
  percentage_train_size: 70
  lstm_units: 128
  return_sequences: true
  second_lstm_layer: false
  use_dropouts: true
  dropout_value: 0.5
  training_epochs: 50
  training_batch_size: 1
