selection:
  method: filter
  target: request_help
  number_of_features: 20
  high_correlation: 0.85
  drop_columns: [exercise_is_evaluation, valid_solution, finished_exercise, exercise_valid_solution,
    student_motivation, grade]
  heatmap_correlation_path_before: dvc_plots/heatmap_correlation_before.png
  heatmap_correlation_path_after: dvc_plots/heatmap_correlation_after.png

model:
  mask_value: -1
  percentage_train_size: 70
  lstm_units: 256
  return_sequences: true
  second_lstm_layer: false
  use_dropouts: false
  dropout_value: 0.5
  training_epochs: 50
  training_batch_size: 1
  show_summary: true
